# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bii.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.InputFiles = QtGui.QWidget()
        self.InputFiles.setObjectName(_fromUtf8("InputFiles"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.InputFiles)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.InputFiles)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rgti_file_edit = QtGui.QLineEdit(self.InputFiles)
        self.rgti_file_edit.setObjectName(_fromUtf8("rgti_file_edit"))
        self.horizontalLayout_2.addWidget(self.rgti_file_edit)
        self.rgti_file_button = QtGui.QPushButton(self.InputFiles)
        self.rgti_file_button.setObjectName(_fromUtf8("rgti_file_button"))
        self.horizontalLayout_2.addWidget(self.rgti_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.InputFiles)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Ndp_file_edit = QtGui.QLineEdit(self.InputFiles)
        self.Ndp_file_edit.setObjectName(_fromUtf8("Ndp_file_edit"))
        self.horizontalLayout_3.addWidget(self.Ndp_file_edit)
        self.Ndp_file_button = QtGui.QPushButton(self.InputFiles)
        self.Ndp_file_button.setObjectName(_fromUtf8("Ndp_file_button"))
        self.horizontalLayout_3.addWidget(self.Ndp_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.InputFiles)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ofm_file_edit = QtGui.QLineEdit(self.InputFiles)
        self.ofm_file_edit.setObjectName(_fromUtf8("ofm_file_edit"))
        self.horizontalLayout_4.addWidget(self.ofm_file_edit)
        self.ofm_file_button = QtGui.QPushButton(self.InputFiles)
        self.ofm_file_button.setObjectName(_fromUtf8("ofm_file_button"))
        self.horizontalLayout_4.addWidget(self.ofm_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(self.InputFiles)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.blocks_file_button_2 = QtGui.QLineEdit(self.InputFiles)
        self.blocks_file_button_2.setObjectName(_fromUtf8("blocks_file_button_2"))
        self.horizontalLayout_5.addWidget(self.blocks_file_button_2)
        self.blocks_file_button = QtGui.QPushButton(self.InputFiles)
        self.blocks_file_button.setObjectName(_fromUtf8("blocks_file_button"))
        self.horizontalLayout_5.addWidget(self.blocks_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_5 = QtGui.QLabel(self.InputFiles)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.cells_file_edit = QtGui.QLineEdit(self.InputFiles)
        self.cells_file_edit.setObjectName(_fromUtf8("cells_file_edit"))
        self.horizontalLayout_6.addWidget(self.cells_file_edit)
        self.cells_file_button = QtGui.QPushButton(self.InputFiles)
        self.cells_file_button.setObjectName(_fromUtf8("cells_file_button"))
        self.horizontalLayout_6.addWidget(self.cells_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.load_input_files_button = QtGui.QPushButton(self.InputFiles)
        self.load_input_files_button.setObjectName(_fromUtf8("load_input_files_button"))
        self.horizontalLayout_8.addWidget(self.load_input_files_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.input_file_help_text = QtGui.QTextBrowser(self.InputFiles)
        self.input_file_help_text.setObjectName(_fromUtf8("input_file_help_text"))
        self.verticalLayout_3.addWidget(self.input_file_help_text)
        self.tabWidget.addTab(self.InputFiles, _fromUtf8(""))
        self.BlockSelect = QtGui.QWidget()
        self.BlockSelect.setObjectName(_fromUtf8("BlockSelect"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.BlockSelect)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.BlockSelect)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.toolBox = QtGui.QToolBox(self.BlockSelect)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 778, 377))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textEdit = QtGui.QTextEdit(self.page)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_9 = QtGui.QPushButton(self.page)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 778, 377))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.toolBox)
        self.pushButton_7 = QtGui.QPushButton(self.BlockSelect)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.tabWidget.addTab(self.BlockSelect, _fromUtf8(""))
        self.OutputPlots = QtGui.QWidget()
        self.OutputPlots.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.RussianFederation))
        self.OutputPlots.setObjectName(_fromUtf8("OutputPlots"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OutputPlots)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.matplotlibwidget = MatplotlibWidget(self.OutputPlots)
        self.matplotlibwidget.setObjectName(_fromUtf8("matplotlibwidget"))
        self.gridLayout_2.addWidget(self.matplotlibwidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dateEdit = QtGui.QDateEdit(self.OutputPlots)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout.addWidget(self.dateEdit)
        spacerItem2 = QtGui.QSpacerItem(54, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtGui.QPushButton(self.OutputPlots)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtGui.QSpacerItem(32, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.dateEdit_2 = QtGui.QDateEdit(self.OutputPlots)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout.addWidget(self.dateEdit_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.OutputPlots, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuHelp_2 = QtGui.QMenu(self.menubar)
        self.menuHelp_2.setObjectName(_fromUtf8("menuHelp_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionClear_Data = QtGui.QAction(MainWindow)
        self.actionClear_Data.setObjectName(_fromUtf8("actionClear_Data"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionClear_Data)
        self.menuHelp.addAction(self.actionExit)
        self.menuHelp_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "RGTI file                                     ", None))
        self.rgti_file_button.setText(_translate("MainWindow", "...", None))
        self.label_2.setText(_translate("MainWindow", "90dp pressures an PIs", None))
        self.Ndp_file_button.setText(_translate("MainWindow", "...", None))
        self.label_3.setText(_translate("MainWindow", "OFm report of injection and BHP", None))
        self.ofm_file_button.setText(_translate("MainWindow", "...", None))
        self.label_4.setText(_translate("MainWindow", "Blocks mapping", None))
        self.blocks_file_button.setText(_translate("MainWindow", "...", None))
        self.label_5.setText(_translate("MainWindow", "Cells mapping", None))
        self.cells_file_button.setText(_translate("MainWindow", "...", None))
        self.load_input_files_button.setText(_translate("MainWindow", "Load input files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputFiles), _translate("MainWindow", "Input files", None))
        self.label_6.setText(_translate("MainWindow", "Enter list of blocks or select them", None))
        self.pushButton_9.setText(_translate("MainWindow", "Read from file", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Enter blocks list for analysis", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Select Blocks", None))
        self.pushButton_7.setText(_translate("MainWindow", "Load Blocks List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BlockSelect), _translate("MainWindow", "Blocks/Patterns select", None))
        self.pushButton.setText(_translate("MainWindow", "Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OutputPlots), _translate("MainWindow", "Plots", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Main", None))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionClear_Data.setText(_translate("MainWindow", "Clear Data", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

from matplotlibwidget import MatplotlibWidget
